// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh7BQ8KgGKT2qEyZFR0-3ka0zRx0gveN8',
    appId: '1:532023367488:web:c7336a07983d7dfc474ca5',
    messagingSenderId: '532023367488',
    projectId: 'chatting-69522',
    authDomain: 'chatting-69522.firebaseapp.com',
    storageBucket: 'chatting-69522.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfXbCZt3WZBlFoMuf6NIX6ZDTz4-21lA',
    appId: '1:532023367488:android:312a0654a6cb1745474ca5',
    messagingSenderId: '532023367488',
    projectId: 'chatting-69522',
    storageBucket: 'chatting-69522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1m4BLduBL3Oc2pdq4bSEPeRewT_kFGW4',
    appId: '1:532023367488:ios:4c3c1d68e425ae5b474ca5',
    messagingSenderId: '532023367488',
    projectId: 'chatting-69522',
    storageBucket: 'chatting-69522.appspot.com',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1m4BLduBL3Oc2pdq4bSEPeRewT_kFGW4',
    appId: '1:532023367488:ios:21a7bcf9a1b38ad2474ca5',
    messagingSenderId: '532023367488',
    projectId: 'chatting-69522',
    storageBucket: 'chatting-69522.appspot.com',
    iosBundleId: 'com.example.firebaseproject.RunnerTests',
  );
}
